export enum PaymentMethod {
  BB_TRANSFER = 'BB_TRANSFER',
  BRADESCO_TRANSFER = 'BRADESCO_TRANSFER',
  ITAU_TRANSFER_GENERIC = 'ITAU_TRANSFER_GENERIC',
  ITAU_TRANSFER_PF = 'ITAU_TRANSFER_PF',
  ITAU_TRANSFER_PJ = 'ITAU_TRANSFER_PJ',
  ITAU_DI = 'ITAU_DI',
  SANTANDER_TRANSFER = 'SANTANDER_TRANSFER',
  SANTANDER_DI = 'SANTANDER_DI',
  CEF_TRANSFER = 'CEF_TRANSFER',
  ORIGINAL_TRANSFER = 'ORIGINAL_TRANSFER',
  INTER_TRANSFER = 'INTER_TRANSFER',
  BS2_TRANSFER = 'BS2_TRANSFER',
  OUTROS_BANCOS = 'OUTROS_BANCOS'
}
